// qwikJsLearning2023/upbeat-qwik-app/src/components/shared/sidebar-item/sidebar-item.tsx
// FILE: components/shared/sidebar-item/sidebar-item.tsx
// _________________________________________

import { $, component$ } from '@builder.io/qwik';
import { useNavigate } from '@builder.io/qwik-city';
import { useFormattedOutput } from '~/utils/utils';
import styles from '~/components/sidebar/sidebar.module.css';
// _________________________________________

type SidebarItemProps = {
  name?: string;
  icon?: string;
  route?: string;
  customClass?: string
};
// _________________________________________

export const SidebarItem = component$<SidebarItemProps>(
  ({ name, icon, route, customClass }) => {
    const navigateTo = useNavigate();
    // ________________ [functions] __________________
    
    const moveToPage = $(() => {
      useFormattedOutput({
        strArg: `🚩 Navigated to: ${ route }` || 'NO ROUTE FOUND',
      });
      // if (route) navigateTo.path = route;
    });
    // _______________________________________________
    return (
      <div onClick$={ moveToPage }
           class={ `${ styles.hoverEffect } ${ customClass }` }>
        <span>
          <i class={ `uil ${ icon }` }></i>
        </span>
        <span class='ml-3 text-sm'>
          <>{ name }</>
        </span>
      </div>
    );
  },
);
// _______________________________________________

// ReactTSLearning2023/next-spotify-clone/components/shared/side-bar-item/SidebarItem.tsx
'use client';
// FILE: components/shared/SidebarItem.tsx
// _______________________________________________

import Link from "next/link";
import { IconType } from "react-icons";
import { twMerge } from "tailwind-merge";
import styles from 'components/shared/side-bar-item/side-bar-item.module.css';
// _______________________________________________

type SidebarItemProps = {
	icon: IconType;
	label: string;
	active?: boolean;
	href: string;
};
// _______________________________________________

const SidebarItem = ({ icon: Icon, label, active, href }: SidebarItemProps) => {
	
	// _________________ [functions] ___________________
	
	
	// _________________________________________________
	return (
		<Link
			className={ twMerge(styles.link, active && 'text-white') }
			href={ href }
		>
			{ /*|====== icon ======|*/ }
			<Icon size={ 26 } />
			{ /*|====== label ======|*/ }
			<p className="truncate w-full">{ label }</p>
		</Link>
	);
};
// _______________________________________________

export default SidebarItem;
// _______________________________________________
