// qwikJsLearning2023/poke-qwik/src/components/shared/navbar/navbar.tsx
// FILE: navbar.tsx
// _________________________________________
// _________________________________________

import { component$ } from '@builder.io/qwik';
import { Link } from "@builder.io/qwik-city";
import styles from '~/components/shared/navbar/navbar.module.css';
// _________________________________________

export const NavBar = component$(() => {
	
	// _________________ functions ___________________
	
	// _______________________________________________
	return (
		<header class={ styles.header }>
			<nav>
        {/* logo-image also `Home` link */ }
				<Link href="/">
					<img src="/bulbasaur_transparent.png" alt="LOGO" />
				</Link>
				{/* site title in navbar */ }
				<h1>Poke-Qwik</h1>
				{/* list of links ========================== */ }
				<ul class="font-medium">
					{/* Home */ }
					<li>
            <Link href="/">Home</Link>
          </li>
					{/* SSR-List */ }
					<li>
			      <Link href="/pokemons/list-ssr">SSR-List</Link>
		      </li>
					{/* Client-List */ }
					<li>
						<Link href="/pokemons/list-client">Client-List</Link>
					</li>
        </ul>
      </nav>
    </header>
	);
});
// _______________________________________________

// ReactTSLearning2023/next-ts-flexibble/components/Navbar.tsx
"use client";
// FILE: components/Navbar.tsx
// _______________________________________________

import AuthProviders from "@/components/providers/AuthProviders";
import { NavLinks } from "@/constants";
import { NavLinkType } from "@/types/link.types";
import Link from "next/link";
import Image from "next/image";
// _______________________________________________

// type NavbarProps = {
// 	mockProp?: string;
// };
// _______________________________________________

const Navbar = () => {
  const session = {};
  
  // _________________ [functions] ___________________
  
  // _________________________________________________
  return (
    <nav className="flexBetween navbar">
      <div className="flex-1 flexStart gap-10">
        {/*|====== Image-link ======|*/ }
        <Link href="/">
          <Image src="/logo.svg" width={ 115 } height={ 43 } alt="Flexible" />
        </Link>
        
        {/*|====== list-of-links ======|*/ }
        <ul className="xl:flex hidden text-small gap-7">
          { NavLinks.map((link: NavLinkType) => (
            <Link href={ link.href } key={ link.key }>
              { link.text }
            </Link>
          )) }
        </ul>
      </div>
      
      <div className="flexCenter gap-4">
        {
          session ?
            (
              <>
            UserPhoto
            <Link href="/create-project">
              Share your work
            </Link>
          </>
            ) :
            (<AuthProviders />)
        }
      </div>
    </nav>
  );
};
// _______________________________________________

export default Navbar;
// _______________________________________________
